In [4]:
import pandas as pd
import numpy as np

In [1]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [6]:
# Load the Data
exoplanets = pd.read_csv("PSCompPars_2026.07.28_21.55.36.csv", comment='#')

In [9]:
exoplanets

      discoverymethod  disc_year
0     Radial Velocity       2007
1     Radial Velocity       2009
2     Radial Velocity       2008
3     Radial Velocity       2002
4     Radial Velocity       1996
...               ...        ...
6319  Radial Velocity       1996
6320  Radial Velocity       1999
6321  Radial Velocity       1999
6322  Radial Velocity       2021
6323  Radial Velocity       2007

[6324 rows x 2 columns]

In [7]:
# List of discovery types
x = np.array(exoplanets["discoverymethod"])
discovery_types = np.unique(x)

In [8]:
discovery_types

array(['Astrometry', 'Disk Kinematics', 'Eclipse Timing Variations',
       'Imaging', 'Microlensing', 'Orbital Brightness Modulation',
       'Pulsar Timing', 'Pulsation Timing Variations', 'Radial Velocity',
       'Transit', 'Transit Timing Variations'], dtype=object)

In [10]:
# List of years
year_start = min(exoplanets["disc_year"])
year_end = max(exoplanets["disc_year"])
print(year_start, " - ", year_end)

1992  -  2026

In [11]:
# Make array of years and types
exoplanets_years = pd.DataFrame()
for year in range(year_start, year_end+1):
  discovery_type_list = []
  for index, discovery_type in enumerate(discovery_types):
    numPlanets = 0
    if year > year_start:
      # numplanets is the cumulative total.
      numPlanets = exoplanets_years.at[index,year-1]
    numPlanets += pd.Series.sum((exoplanets['disc_year'] == year) & (exoplanets['discoverymethod'] == discovery_type))
    discovery_type_list.append(numPlanets)
  exoplanets_years[year] = discovery_type_list
exoplanets_years.insert(0, "Discovery Type", discovery_types)

In [12]:
exoplanets_years

,Discovery Type,1992,1993,1994,1995,1996,1997,1998,1999,2000,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
0,Astrometry,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,2,3,3,6,6
1,Disk Kinematics,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,1,1,1,1,1
2,Eclipse Timing Variations,0,0,0,0,0,0,0,0,0,...,11,12,14,14,14,16,17,17,17,17
3,Imaging,0,0,0,0,0,0,0,0,0,...,47,50,54,57,62,66,73,84,92,98
4,Microlensing,0,0,0,0,0,0,0,0,0,...,55,76,90,110,131,182,212,240,263,281
5,Orbital Brightness Modulation,0,0,0,0,0,0,0,0,0,...,6,6,6,6,9,9,9,9,9,9
6,Pulsar Timing,2,2,3,3,3,3,3,3,3,...,7,7,7,7,7,7,7,8,8,8
7,Pulsation Timing Variations,0,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
8,Radial Velocity,0,0,0,1,7,8,14,27,43,...,671,709,774,820,897,1013,1069,1098,1159,1195
9,Transit,0,0,0,0,0,0,0,0,0,...,2775,3019,3126,3290,3747,3938,4162,4349,4493,4667
10,Transit Timing Variations,0,0,0,0,0,0,0,0,0,...,17,18,20,21,22,24,28,32,38,40

In [13]:
exoplanets_years.to_csv(index=False)

'Discovery Type,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026\nAstrometry,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,2,3,3,6,6\nDisk Kinematics,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1\nEclipse Timing Variations,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,3,8,9,9,9,10,10,11,12,14,14,14,16,17,17,17,17\nImaging,0,0,0,0,0,0,0,0,0,0,0,0,3,4,9,10,17,17,23,26,28,35,37,42,44,47,50,54,57,62,66,73,84,92,98\nMicrolensing,0,0,0,0,0,0,0,0,0,0,0,0,1,3,4,4,8,10,12,13,20,25,31,35,45,55,76,90,110,131,182,212,240,263,281\nOrbital Brightness Modulation,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,3,6,6,6,6,6,6,6,9,9,9,9,9,9\nPulsar Timing,2,2,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,5,5,5,5,5,5,7,7,7,7,7,7,7,8,8,8\nPulsation Timing Variations,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2\nRadial Velocity,0,0,0,1,7,8,14,27,43,55,83,104,122,155,176,210,246,312,349,398,437,471,519,565,623,671,709,774,820,897,1013,1069,1098,1159,1195\nTransit,0,0,0,0,0,0,0,0,0,0,1,1,6,6,11,27,42,60,106,186,280,359,1157,1256,2688,2775,3019,3126,3290,3747,3938,4162,4349,4493,4667\nTransit Timing Variations,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,3,15,15,16,17,18,20,21,22,24,28,32,38,40\n'

In [14]:
exoplanets_years.to_csv('exoplanet_years_formatted.csv', index=False)